import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { z } from "zod";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const url = window.location.origin;
  const [shortUrl, setShortUrl] = useState("");

  const getShortUrl = api.shortUrlRouter.shortenUrl.useMutation({
    onSuccess: (data) => {
      console.log("successfully saved in db!");
      setShortUrl(data.shortUrl);
    },
    onError: (error) => {
      console.error("failed ", error);
    },
  });

  const [longUrl, setLongUrl] = useState("");

  const fetchLongUrl = api.shortUrlRouter.fetchLongUrl.useQuery(
    {
      shortUrl: shortUrl,
    },
    {
      enabled: !!shortUrl,
      staleTime: Infinity,
      cacheTime: Infinity,
    }
  );

  // const fetchAll = api.shortUrlRouter.fetchAll.useQuery();

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    getShortUrl.mutate({
      longUrl,
    });

    setLongUrl("");
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-10 border-blue-200 bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <form
          onSubmit={handleSubmit}
          className="flex flex-col gap-4 justify-center items-center p-4 w-5/6 md:w-1/3"
        >
          <label className="text-3xl md:text-4xl text-white">Enter a valid long url</label>
          <input
            onChange={(e) => setLongUrl(e.target.value)}
            className="p-4 w-full text-indigo-500 text-lg font-bold bg-blue-200 rounded-xl"
            type="text"
            value={longUrl}
          />
          <button
            className="p-4 w-2/3 md:w-1/3 text-2xl text-white rounded-full bg-white/10 disabled:bg-white/5"
            type="submit"
            disabled={!z.string().url().safeParse(longUrl).success}
          >
            Shorten
          </button>
        </form>
        {shortUrl !== "" && (
          <div className="flex flex-col gap-2 p-4 rounded-xl border border-white">
            <p className="p-4 text-xl md:text-3xl text-center items-center text-white bg-clip-text rounded-xl">
              Success!
            </p>
            <div className="flex flex-col lg:flex-row gap-4 items-center p-4">
              <p className="text-2xl text-white">Long: </p>
              <p className="py-2 px-4 rounded-xl text-xl md:text-3xl text-transparent bg-clip-text bg-gradient-to-r from-yellow-500 via-green-500 to-blue-500 border-2">
                {fetchLongUrl.data}
              </p>
              <p className="text-2xl text-white">Short: </p>
              <p className="py-2 px-4 text-xl md:text-3xl text-transparent bg-clip-text bg-gradient-to-r from-yellow-500 via-green-500 to-blue-500 rounded-xl border-2">
                <Link href={`${url}/${shortUrl}`} target="_blank">
                  {url}/{shortUrl}
                </Link>
              </p>
            </div>
          </div>
        )}
        {/* <table className="w-1/2 text-left"> */}
        {/*   <caption className="py-5 px-10 text-lg font-semibold text-left text-white bg-blue-900"> */}
        {/*     All Urls */}
        {/*   </caption> */}
        {/*   <thead className="text-sm text-white uppercase bg-blue-500"> */}
        {/*     <tr> */}
        {/*       <th scope="col" className="py-3 px-10"> */}
        {/*         Long */}
        {/*       </th> */}
        {/*       <th scope="col" className="py-3 px-10"> */}
        {/*         Short */}
        {/*       </th> */}
        {/*     </tr> */}
        {/*   </thead> */}
        {/*   <tbody> */}
        {/*     {fetchAll.data?.map(({shortUrl, longUrl}) => ( */}
        {/*       <tr key={shortUrl} className="text-lg text-white bg-blue-900"> */}
        {/*         <td className="py-3 px-10">{longUrl}</td> */}
        {/*         <td className="py-3 px-10"><Link href={`${url}/${shortUrl}`} target="_blank">{url}/{shortUrl}</Link></td> */}
        {/*       </tr> */}
        {/*     ))} */}
        {/*   </tbody> */}
        {/* </table> */}
      </main>
    </>
  );
};

export default Home;
